@startuml 03. Business Context
caption Business Context

skinparam componentStyle uml2

frame "Business Context" {
    actor "User" as u
    actor "Agent" as a

    rectangle "POWA" {

        node "Messaging" as m <<system>>
        node "Processes" as p <<system>>
    }


    a --> m: Works with Messaging\nand answers\ncustomer questions
    a --> p: Create / extend processes\nfor the user on the basis of the chat

    u --> m: Chats with an agent regarding \na concern
    u <.. m: Recieves answers\nsolutions for his concern


    m . p: Chat as input for ticket
}

@enduml